# fly.toml app configuration file generated for protohackers-quiet-river-8199 on 2024-08-25T14:03:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'protohackers-quiet-river-8199'
primary_region = 'arn'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 5005
# force_https = true
# auto_stop_machines = 'stop'
# auto_start_machines = true
# min_machines_running = 0
processes = ['app']
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = []
port = 5005

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
