# fly.toml app configuration file generated for protohackers-quiet-river-8199 on 2024-08-25T14:03:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'protohackers-quiet-river-8199'
primary_region = 'arn'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 5005
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5005

[[services]]
internal_port = 5006
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5006

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[services.concurrency]
min_machines_running = 0
auto_start_machines = true
auto_stop_machines = "stop"
hard_limit = 15
soft_limit = 10
type = "connections"

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
